PickemApp/ViewModels/Home.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using PickemApp.Models;

namespace PickemApp.ViewModels
{
    public class HomeNavLogin
    {
        public Player CurrentPlayer { get; set; }
    }
}

PickemApp/Controllers/HomeController.cs
using System;
using System.Configuration;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PickemApp.SyncUtils;
using PickemApp.Models;
using PickemApp.ViewModels;

using WebMatrix.WebData;

namespace PickemApp.Controllers
{
    public class HomeController : Controller
    {
        private PickemDBContext db = new PickemDBContext();

        public ActionResult Index()
        {
            //doing the sync here, which is ugly, but will have to suffice until I found a way to do it in the background.
            //2014-09-06: using CloudScheduler now so I can stop doing this!
            //NflSync.UpdateGames("http://www.nfl.com/liveupdate/scorestrip/ss.xml");

            int year = ConfigurationManager.AppSettings["currentYear"] != null ? Convert.ToInt32(ConfigurationManager.AppSettings["currentYear"]) : DateTime.Today.Year;

            ViewBag.Year = year;

            //get all of the weeks
            var weeks = (from v in db.vwWeeklyPlayerPicks
                         where v.Year == year && v.Rank == 1
                         orderby v.Week
                         select new WeeklyPlayerPicks
                         {
                             WeekNumber = v.Week,
                             Year = v.Year,
                             Player = v.Player
                         }).ToList();

            return View(weeks);
        }

        [ChildActionOnly]
        public ActionResult NavLogin()
        {
            var user = Auth.User;
            return View(new HomeNavLogin { CurrentPlayer = user });
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PickemApp/Controllers/PicksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Dapper;

using PickemApp.Models;
using PickemApp.ViewModels;

using WebMatrix.WebData;

namespace PickemApp.Controllers
{
    [Authorize]
    public class PicksController : Controller
    {
        private PickemDBContext db = new PickemDBContext();

        public ActionResult Index(int? week, int? year)
        {
            if (!week.HasValue || ! year.HasValue)
            {
                var game = db.Games.Where(g => g.GameType == "REG").OrderByDescending(g => g.Year).ThenByDescending(g => g.Week).FirstOrDefault();
                if (game == null)
                    return HttpNotFound();

                return RedirectToAction("Index", new { week = game.Week, year = game.Year });
            }

            ViewBag.Deadline = PickemApp.Models.Season.GetDeadline(week.Value, year.Value);
            ViewBag.PastDeadline = (DateTime.Now >= PickemApp.Models.Season.GetDeadline(week.Value, year.Value));

            var user = Auth.User;

            var vm = new PicksIndex();

            vm.CurrentPlayer = user;
            vm.CurrentWeek = new Week(week.Value, year.Value);

            //get all of the weeks
            vm.Weeks = (from g in db.Games
                        where g.Year == year && g.GameType == "REG"
                        select new Week
                        {
                            WeekNumber = g.Week,
                            Year = g.Year
                        }).Distinct().ToList();

            using (var conn = db.Database.Connection)
            {
                string sql = @"select p.Id, p.TeamPicked, p.TotalPoints, p.PickResult, g.Id as GameId, g.HomeTeam, g.VisitorTeam, g.WinningTeam
                            from Games g 
                            left outer join Picks p on g.Id = p.GameId and p.PlayerId = @playerId
                            where g.Week = @week and g.Year = @year and g.GameType = 'REG'
                            order by left(g.Eid, 8), RIGHT('00000' + ISNULL(g.Time, ''), 5), g.Gsis";

                vm.Picks = conn.Query<PickRadio>(sql,
                param: new { week = week, year = year, playerId = user.Id }).ToList();
            }
            
            return View(vm);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Index(int week, int year, PicksIndex form)
        {
            var user = Auth.User;
            form.CurrentPlayer = user;
            form.CurrentWeek = new Week(week, year);

            //get all of the weeks
            form.Weeks = (from g in db.Games
                        where g.Year == year && g.GameType == "REG"
                        select new Week
                        {
                            WeekNumber = g.Week,
                            Year = g.Year
                        }).Distinct().ToList();

            if (ModelState.IsValid)
            {
                var picks = form.Picks.Select(p => new Pick 
                { 
                    Id = p.Id,
                    PlayerId = user.Id,
                    GameId = p.GameId,
                    TeamPicked = p.TeamPicked,
                    TotalPoints = p.TotalPoints,
                    PickResult = p.PickResult
                });

                foreach (var pick in picks)
                {
                    if (pick.Id != 0)
                    {
                        db.Entry(pick).State = System.Data.Entity.EntityState.Modified;
                    }
                    else
                    {
                        db.Picks.Add(pick);
                    }
                }

                db.SaveChanges();

                return RedirectToAction("Index", new { week = week, year = year});
            }

            Response.Write(form.Picks.Count);

            return View("Index", form);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PickemApp/Controllers/SyncController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PickemApp.SyncUtils;
using PickemApp.Models;

namespace PickemApp.Controllers
{
    public class SyncController : Controller
    {
        //
        // GET: /Sync/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Nfl(string x = "https://ramcasleague.droppages.com/NflScores2.xml", int v = 1)
        {
            if (string.IsNullOrEmpty(x))
            {
                return HttpNotFound();
            }

            ViewBag.Message = "Games and pick results updated.";

            NflSync.UpdateGames(x, v);
            return View("Index");
        }

        [Authorize(Roles = "admin")]
        public ActionResult Picks(string h = "")
        {
            if (!string.IsNullOrEmpty(h))
            {
                if (h.Contains(".xls"))
                {
                    PickSync.UpdatePicksXls(h);
                }
                else
                {
                    PickSync.UpdatePicks(h);
                }

                ViewBag.Message = "Picks updated.";

                return View("Index");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Picks(HttpPostedFileBase file)
        {

            if (file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/datafiles"), fileName);
                file.SaveAs(path);

                if (fileName.Contains(".xls"))
                {
                    PickSync.UpdatePicksXls(fileName);
                }
                else if (fileName.Contains(".csv"))
                {
                    PickSync.UpdatePicksCsv(fileName);
                }
                else
                {
                    PickSync.UpdatePicks(fileName);
                }

                ViewBag.Message = "Picks updated.";
            }

            return View("Index");
            //return RedirectToAction("Index");
        }
    }
}

PickemApp/Controllers/WeekController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PickemApp.Models;
using PickemApp.SyncUtils;
using PickemApp.ViewModels;

namespace PickemApp.Controllers
{
    public class WeekController : Controller
    {
        private PickemDBContext db = new PickemDBContext();

        public ActionResult Index(int week, int year, bool completed = false)
        {
            //doing the sync here, which is ugly, but will have to suffice until I found a way to do it in the background.
            //2014-09-06: using CloudScheduler now so I can stop doing this!
            //NflSync.UpdateGames("http://www.nfl.com/liveupdate/scorestrip/ss.xml");

            var vm = new WeekIndex();

            vm.CurrentWeek = new Week(week, year);

            //get all of the weeks
            vm.Weeks = (from g in db.Games
                             where g.Year == year && g.GameType == "REG"
                             select new Week
                             {
                                 WeekNumber = g.Week,
                                 Year = g.Year
                             }).Distinct().ToList();

            if (DateTime.Now > PickemApp.Models.Season.GetDeadline(week, year))
            {
                var listLeaders = WeeklyPlayerPicks.GetWeeklyLeaders(week, year, completed);
                vm.Leaders = listLeaders.ToList();
            }

            var games = db.Games.Where(q => q.Week == week && q.Year == year && q.GameType == "REG").ToList();
            vm.Games = games.OrderBy(o => o.Eid.Substring(0, 8)).ThenBy(o => o.Time.PadLeft(5, '0')).ThenBy(o => o.Gsis).ToList();

            return View(vm);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PickemApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

PickemApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

PickemApp/Views/Home/Index.cshtml
@model IEnumerable<PickemApp.Models.WeeklyPlayerPicks>

@{
    ViewBag.Title = "Weekly Winners";
}

<h2>@ViewBag.Year Season</h2>

<table class="standings">
@foreach (var week in Model)
{
    <tr>
        <th scope="row">@Html.ActionLink((string)string.Format("Week {0}", week.WeekNumber), "Index", "Week", new { week = @week.WeekNumber, year = @week.Year }, null)</th>
        <td>@week.Player.Name</td>
    </tr>
}
</table>

PickemApp/Views/Home/NavLogin.cshtml
@model PickemApp.ViewModels.HomeNavLogin
@{
    Layout = null;
}


<ul class="nav navbar-nav navbar-right">
    @if (Request.IsAuthenticated)
    {
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@Model.CurrentPlayer.Name <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="@Url.Action("Index", "Profile")">Profile</a></li>
                <li><a href="@Url.Action("Stats", "Profile", new { id = string.Empty })">Stats</a></li>
                <li><a href="@Url.Action("Index", "Picks")">Picks</a></li>
                @if (User.IsInRole("admin"))
                {
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Admin</li>
                    <li><a href="@Url.Action("Picks", "Sync")">Upload Picks</a></li>
                    <li><a href="@Url.Action("Index", "Player")">Players</a></li>
                }
                <li role="separator" class="divider"></li>
                <li>
                    <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        @Html.AntiForgeryToken()
                    }
                </li>
            </ul>
        </li>
    }
    else
    {
        <li><a href="@Url.Action("Login", "Account")">Login</a></li>
    }
</ul>